server:
  port: 49030

spring:
  application:
    name = myGateway     
  cloud:
    gateway:
      routes:
         - id: service-a
           uri: http://localhost:49031
           predicates:
             - Path=/service-a/**
           filters:
             - AddRequestHeader=Authorization, Bearer abc123
             - AddRequestHeader=X-User-Role, admin

         - id: service-b
           uri: http://localhost:49032
           predicates:
             - Path=/service-b/**
           filters:
             - name: CircuitBreaker
               args:
                 name: serviceACircuitBreaker
                 fallbackUri: forward:/fallback/service-b

         - id: python-service
           uri: http://localhost:5000
           predicates:
             - Path=/python-service/**

springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: Service A
        url: /service-a/v3/api-docs
      - name: Service B
        url: /service-b/v3/api-docs
      - name: Python Service
        url: /python-service/openapi.json