server:
  port: 49030

spring:
  application:
    name: myGateway     
  cloud:
    gateway:
      routes:
         - id: service-a
           uri: lb://serviceA
           predicates:
             - Path=/old-service-a/**
           filters:
             - AddRequestHeader=Authorization, Bearer abc123
             - AddRequestHeader=X-User-Role, admin
             - RewritePath=/old-service-a/(?<segment>.*), /service-a/${segment}

         - id: service-b
           uri: lb://serviceB
           predicates:
             - Path=/service-b/**
           filters:
             - name: AuthGatewayFilter
               args:
                 debugMode: Enabled

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka