server:
  port: 49030

spring:
  application:
    name = myGateway     
  cloud:
    gateway:
      routes:
         - id: service-a
           uri: http://localhost:49031
           predicates:
             - Path=/old-service-a/**
           filters:
             - AddRequestHeader=Authorization, Bearer abc123
             - AddRequestHeader=X-User-Role, admin
             - RewritePath=/old-service-a/(?<segment>.*), /service-a/${segment}

         - id: service-b
           uri: http://localhost:49032
           predicates:
             - Path=/service-b/**
           filters:
             - name: AuthGatewayFilter
               args:
                 debugMode: Enabled
             - name: RequestRateLimiter
               args:
                 redis-rate-limiter.replenishRate: 1  # requests per second
                 redis-rate-limiter.burstCapacity: 1
                 key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: 10.10.33.248
      port: 6379

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG


